### ISSUE TITLE
Undesired behavior of _check_and_fill_tracking_data_size

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#150]
https://github.com/pyomeca/BiorbdOptim/blob/e904785389195467739539f8bf78910092d7e234/biorbd_optim/penalty.py#L493

This test crashes when data_to_track is a np.ndarray of the right shape but filled with zeros. 
The first part of the logical test is False, so it evaluates the second part which is not defined with a np.ndarray:

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

Although I understand that only a 0 was expected when tracking a null vector, I believe this behavior to be undesired. E.g. in my case, I am creating a lot of different penalties in a for loop, and some times, the data_to_track can be a null vector.

**Comment by fbailly** [comment]
I'm opening an issue on this matter because I believe that this rationale was used in several places of the code, and a PR should fix all of them at a time.

**Comment by pariterre** [comment]
This function no longer exists thanks to #351
