### ISSUE TITLE
custom objective/problem/penalty/etc. can't be save with a .bo

### ISSUE THREAD

**Issue by tgouss** [pyomeca/bioptim#156]

**Comment by tgouss** [comment]
In temporary solution, you have to import you custom function when you load .bo like this :

from **up_and_down_bow** import **xia_model_dynamic**, **xia_model_configuration**

**Comment by pariterre** [comment]
This seems to be okay now, as long as the custom function is not inside another class... This is a bit tricky though... We will have dig a bit deeper. I am leaving this PR open anyway

**Comment by pariterre** [comment]
My last message is the right way to solve this. This is a `pickle` limitation and cannot be circumvented otherwise
