### ISSUE TITLE
Implement update_intial_guess in the same way as update_objectives, update_constraints, etc.

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#196]
arguments to this function should be two (optional) InitialConditionsList(), one for x and one for u, which modify ocp.V_init.init.

**Comment by pariterre** [comment]
This will imply to have a variable that keeps the initial values for the initial guesses. 
Also, solver_option should allow to [True] update automatically or [False] do not update automatically. 
The latter should be done for both Ipopt and ACADOS

**Comment by Steakkk** [comment]
I'll work on it.

**Comment by Steakkk** [comment]
Working on it, PR #201.

**Comment by pariterre** [comment]
Done
