### ISSUE TITLE
Torques in quaternions

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#229]
When quaternions are mapped, mapping is not considered.
(U_mapping = BidirectionalMapping(Mapping([-1, -1, -1, -1, -1, -1, 6, 7]), Mapping([-1, -1, -1, -1, -1, -1, 6, 7])) gives the graphs attached)

![Capture d’écran de 2020-11-05 10-55-10](https://user-images.githubusercontent.com/50926485/98264519-fb13eb80-1f55-11eb-8d69-6c9e969aacd5.png)

**Comment by pariterre** [comment]
This should now be fixed thanks to #351
