### ISSUE TITLE
Changing solver_options twice for ACADOS

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#245]
It seems that changing the solver options for ACADOS can only be done once. If done twice, it fails. 

For instance 
```python
for i in range (10):
    sol = ocp.solve(solver=Solver.ACADOS, solver_options={"nlp_solver_max_iter": 10})
```
will fail the second time, but 
```python
for i in range (10):
    if i == 0:
        sol = ocp.solve(solver=Solver.ACADOS, solver_options={"nlp_solver_max_iter": 10})
    else: 
        sol = ocp.solve(solver=Solver.ACADOS)
```
will have the expected behavior

**Comment by fbailly** [comment]
Changing max_iter after solver creation is not allowed by acados yet. I asked for this feature addition today.

**Comment by fbailly** [comment]
https://discourse.acados.org/t/modifying-solver-tolerance-after-solver-creation/304/4

**Comment by fbailly** [comment]
I propose to close this for now.
