### ISSUE TITLE
Lagrange in ACADOS should behave the same as IPOPT

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#248]
The last node when using Lagrange objective function is ignore in ACADOS while in Ipopt it is targeted. They should behave the same. Out of simplicity and intuitiveness, I think that the behavior that Ipopt currently has is the appropriate one

**Comment by pariterre** [comment]
If I recall well, this is now done? :)

**Comment by fbailly** [comment]
Yes : https://github.com/pyomeca/bioptim/pull/243 .
