### ISSUE TITLE
Visualize the nodes via an HTML interface

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#296]
It would be nice to be able to visualize the nodes for the objective function and constraint after the OCP is built

**Comment by pariterre** [comment]
Add warnings for muscles activations outside [0; 1] for a sanity check

**Comment by pariterre** [comment]
https://graphviz.org/gallery/

**Comment by pariterre** [comment]
This is done in #304

**Comment by fbailly** [comment]
I suggest we use the following lib based on d3js : https://github.com/swayvil/d3js-tree-boxes

**Comment by pariterre** [comment]
This turns out to be not viable. We are sticking with PDF for now
