### ISSUE TITLE
Check for Conditioning of the problem 

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#306]
Check if the Jacobian of the cost function and the Jacobian and Hessian of the constraints is well-conditioned. Otherwise raise a warning (flag in solve, or in an ocp.method)

**Comment by mickaelbegon** [comment]
perhaps some ideas in : http://faculty.bscb.cornell.edu/~hooker/zebra_desc2.pdf

**Comment by fbailly** [comment]
We should also use visualization tools for these matrices, as in https://gitlab.kuleuven.be/meco-software/rockit

**Comment by EveCharbie** [comment]
> perhaps some ideas in : http://faculty.bscb.cornell.edu/~hooker/zebra_desc2.pdf

Main tricks from this article :
• Imposing loose boundary conditions on the state variables. Although these are not active in the final solution, they help improve the conditioning of the system at intermediate steps.
• Successively increase the set of parameters to be optimized. This helps to keep the Hessian positive definite and provides a sequence of good initialization values for the next optimization problem.
• Consider transformations of the system. These have not been employed here, but the log transform
dx=f(x), y=log(x)⇒ dy=e−yf(ey)
dt                             dt
is commonly found to make system trajectories easier to solve, particularly when they involve large values of f(x).

The AMPL (https://ampl.com) interface for IPOPT is used for parameter estimation, diagnostics and system modifications.

**Comment by pariterre** [comment]
From #456 :
Collaborator
EveCharbie commented [8 days ago](https://github.com/pyomeca/bioptim/issues/456#issue-1200106208)[](https://github.com/EveCharbie)

Add a check before optimization for "how well is written the problem", which would be useful for debugging.
I think it would go as follow: Jacobain rank - dimensions = number of non-linearly independent constraints.
@[EveCharbie](https://github.com/EveCharbie)
Collaborator Author
EveCharbie commented [8 days ago](https://github.com/pyomeca/bioptim/issues/456#issuecomment-1095465787)

Also, if we follow this path, I would suggest we add a check for the convexity of the objective function using the second derivative being positive for the entire domain.
And a check for the equality constraints (being linear I think)

**Comment by EveCharbie** [comment]
@julo0

**Comment by Ipuch** [comment]
#579 last pb is here.
