### ISSUE TITLE
Acados pendulum example is not converging by default

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#336]
I have successfully installed ACADOS on linux using the last version of the script "acados_install.sh".

I've tried the pendulum example in examples\ACADOS directory. However, the problem is not converging when using this command line: 

`sol = ocp.solve(solver=Solver.ACADOS)`

But it is converging when using this:

`sol = ocp.solve(solver=Solver.ACADOS, solver_options={'print_level': 1})`

While it is written by default in acados_interface.py that: 

`self.acados_ocp.solver_options.print_level = 1`

**Comment by fbailly** [comment]
Really strange, must be investigated
