### ISSUE TITLE
plots with different nx/nu

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#341]
Hi,

Here is the error when using ControlType.LINEAR_CONTINUOUS.

Running the command : sol.graphs()

`RuntimeError: .../casadi/core/function_internal.hpp:1257: Input 1 (u) has mismatching shape. Got 3-by-2. Allowed dimensions, in general, are:
 - The input dimension N-by-M (here 3-by-1)
 - A scalar, i.e. 1-by-1
 - M-by-N if N=1 or M=1 (i.e. a transposed vector)
 - N-by-M1 if K*M1=M for some K (argument repeated horizontally)
 - N-by-P*M, indicating evaluation with multiple arguments (P must be a multiple of 6 for consistency with previous inputs)`

**Comment by EveCharbie** [comment]
Also implement add_plot with phase transition and plots with different nx/nu

**Comment by Ipuch** [comment]
phase transition has been solved in #439
