### ISSUE TITLE
Plot objective and constraints values at the solution

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#347]
Graph at each node, to see which constraint is failing and which objective is badly weighted.

**Comment by pariterre** [comment]
@EveCharbie #351 allows this easily now as each of the penalty has a "weighted_function" attribute which is a casadi function of the actual cost/constraint function. calling it with `[states, controls, parameters, weight, target, dt]` returns the value. Please note `weight`, `target` and `dt` are also stored in the penalty!
