### ISSUE TITLE
Sign to oppose in mapping for first index

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#356]
example :
U_mapping = BiMapping([None, None, None, None, None, None, 0, 1, 2, 3, 4, 5, -0], [0, 1, 2, 3, 4 ,5])

0 == -0 -> True

**Comment by mickaelbegon** [comment]
do you see an easy fix? 
what could be -0? NaN, inf
do you recommand providing 3 lists to include a list of direction/signs?

**Comment by EveCharbie** [comment]
Yes, @pariterre and I discussed reintroducing sign_to_oppose as an input :)

**Comment by pariterre** [comment]
@EveCharbie 
This is now fixed in #351 
Thanks for reporting!
