### ISSUE TITLE
Plot of contacts

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#363]
When using ControlType.LINEAR_CONTINOUS, the plot is not actually properly integrated

**Comment by Ipuch** [comment]
The short answer is no.
Should be partially solved with #458 
rectangle integration rule shouldn't be allowed with linear_continuous controls.

In pendulum example, here is the difference between rectangle integration and trapezoidal minimizing torque for 200 shooting nodes:
32.15465160060267 (rectangle)
45.61224011362183 (trapezoidal)

Here is the code I used:
```python
    import numpy as np
    print("qdot")
    print(np.sum(sol.states["qdot"]**2 * 1/n))
    print(np.sum((np.convolve(sol.states["qdot"][0, :], np.ones(2), 'valid') / 2) ** 2 * 1/n)
          + np.sum((np.convolve(sol.states["qdot"][1, :], np.ones(2), 'valid') / 2) ** 2 * 1 / n))

    print("tau")
    print(np.sum(sol.controls["tau"][:,:-1]**2 * 1/n))
    print(np.sum((np.convolve(sol.controls["tau"][0, :], np.ones(2), 'valid') / 2) ** 2 * 1/n)
          + np.sum((np.convolve(sol.controls["tau"][1, :], np.ones(2), 'valid') / 2) ** 2 * 1 / n))
```

**Comment by Ipuch** [comment]
To be closed ?
The only thing that would need to be changed is to raise an Error when 'ControlType.LINEAR_CONTINUOUS' is used and 'integration_rule = IntegralApproximation.RECTANGLE'.
Or do we leave that to the User ?

**Comment by Ipuch** [comment]
@pariterre any opinion on this ?
This issue could be quickly closed, I think :)

**Comment by pariterre** [comment]
I think it makes sense to raise the error. But I am not sure why it is incompatible..

**Comment by Ipuch** [comment]
It is not uncompatible but doesn't make sense to integrate controls with rectangle rules when this is controleType is LINEAR_CONTINUOUS

**Comment by Ipuch** [comment]
It should be closed.
