### ISSUE TITLE
Have a module for multistart OCP which use MPI

### ISSUE THREAD

**Issue by mickaelbegon** [pyomeca/bioptim#393]
https://mpi4py.readthedocs.io/en/stable/

**Comment by pariterre** [comment]
@EveCharbie How far are we from a multistart module?

**Comment by Ipuch** [comment]
#494 
#510 
#506 

This contributed to the MPI to a multistart module.

**Comment by EveCharbie** [comment]
@mickaelbegon why would we prefer to use MPI over multiprocessing? If I am not mistaken, MPI seems to be for communication between the threads.

**Comment by mickaelbegon** [comment]
@EveCharbie it was an idea. Mutiprocessing is fine.

**Comment by pariterre** [comment]
Sorry, I skipped the MPI part in the title. MPI is for passing information between threads, meaning they are on a shared memory schema, which is not something we want. My question to @EveCharbie was there solely about the multistart part. Is this module already available?

**Comment by EveCharbie** [comment]
Good that we are on the same page :) In that case, I began to work on it. @pariterre you should get a PR in the next week.
