### ISSUE TITLE
Modify InterpolationType for initial guess

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#406]
Add an InterpolationType.EACHNODE to provide an initial guess for each knot point where defects are minimized
Modify InterpolationType.EACHFRAME to provide an initial guess for each knot points and intermediate points (in DMS) or collocation points (in DC).

For now InterpolationType.EACHFRAME ask to provide values for each knot points when the ocp is a DMS and every points when its DC.

**Comment by pariterre** [comment]
@Ipuch 
Could you add the snippet you used as a workaround?
