### ISSUE TITLE
Robustness to model parameter variations

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#411]

**Comment by pariterre** [comment]
Please expand!

**Comment by EveCharbie** [comment]
I think this would be in the same idea as #313 (not the same thing, but implementing it at the same time would be efficient).
However, I think that we would need to fix something in biorbd to be able to modify the .bioMod parameters.

**Comment by Ipuch** [comment]
@EveCharbie Can we consider it's treated with multimodel PR #548 ?

**Comment by EveCharbie** [comment]
Roughly, yes :)
