### ISSUE TITLE
Get position of segments for constraints

### ISSUE THREAD

**Issue by MahsaP** [pyomeca/bioptim#432]
Hi,

I would like to calculate the distance between two segments in my model and then set an equality constraint from that. In RBDL, this function CalcBodyToBaseCoordinates simply calculates for example the distance between pelvis and feet. Would you please give me an example in python how I can do it with biorbd and then use it as a constraint?

**Comment by EveCharbie** [comment]
Hi :)
You could use markers and set a constraint for the distance between markers.
Otherwise, you could set a custom constraint using the biorbd function you mentioned (the custom_constraint example could be useful with that).
Feel free to ping me if you have other questions.

**Comment by MahsaP** [comment]
@EveCharbie Thanks a lot for your comment :)

I tried to use custom_constraint example as a reference to define my equality constraint. But it seems the constraint is not active. When I debug it, it doesn't go inside the function and print what I want at the end. 

1- How can I make sure the constraint is active?
2- What is the usage of node? When do we select START, END, ALL, or ALL_SHOOTING?
3- For equality and inequality constraints, is it only possible by defining them through functions? 
4- Is it possible to have access through rbdl in the python for bioptim?

**Comment by EveCharbie** [comment]
Hi,

I will try to answer to your questions here for the benefit of others.
But if you still have questions, I think seeing your code I might be better able to help you out. So you can e-mail me at eve.charbonneau.1@umontreal.ca and we can have a quick call :)

`But it seems the constraint is not active.`
For the constraint to be active you need to call it by "constraint.add([name of your constraint], [arguments of the constraint], [arguments for bioptim like phase or node]). Then, you have to include constraint list as an argument when you call OptimalControlProgram.
`1- How can I make sure the constraint is active?`
You can see it in the PDF of your problem generated with "ocp.print(to_console=False, to_graph=True)" or "ocp.add_plot_penalty(CostType.ALL)" line 116 and 110 from examples/getting_started/pendulum.py
`2- What is the usage of node? When do we select START, END, ALL, or ALL_SHOOTING?`
node.START -> applies to the first node
node.END -> applies to the last node
node.ALL -> applies to all the nodes,
node.ALL_SHOOTING -> applies to all shooting nodes
`3- If I want to solve a multiphase problem, how can I specify it at the end or start of the phase? Is it done through node?`
Yes if you want to add a constraint to the last node of the first phase you would proceed like that "contraint.add(constraintFcn.SUPERIMPOSE_MARKERS, node=Node.END, phase=0, [other arguments])" line 87 from examples/getting_started/example_multiphase.py
`4- For equality and inequality constraints, is it only possible by defining them through functions?`
Yes, you have to either use custom functions or built-in functions.
`5- Is it possible to have access through rbdl in the python for bioptim?`
Yes and No. biorbd is interfaced to work with bioptim. biorbd is an adapted version of RBDL, so you should be able to have access to what you need through biorbd.
