### ISSUE TITLE
Installation of HSL solvers

### ISSUE THREAD

**Issue by MahsaP** [pyomeca/bioptim#443]
Hi,

I would like to use HSL solvers. I installed the library. I would like to follow the instructions on README to include libhsl.so; however, I get libcoinhsl.so after making the file for HSL. Do you have any recommendation to resolve the issue. Thanks!

![ExitMessage](https://user-images.githubusercontent.com/12606874/153932413-7b666af7-8fb2-4f0e-8a09-c98cbe14be95.JPG)

![libcoinhsl](https://user-images.githubusercontent.com/12606874/153932644-1fccc369-ae9f-43d9-8aad-e836544bbc05.JPG)

**Comment by EveCharbie** [comment]
I would suggest you place "libhsl.so" in your environment. Here I see that yours would be env1, so you should place it in a place like /home/[user]/anaconda3/envs/env1/lib.

**Comment by MahsaP** [comment]
The issue I have is the library’s name is “libcoinhsl.sa”. I put in the directory as you mentioned. The name is the library does not match.

**Comment by EveCharbie** [comment]
How did you get this "libcoinhsl.sa" ?
Did you ask for an academic license of hls solvers using this link https://www.hsl.rl.ac.uk/download/coinhsl-archive-linux-x86_64/2014.01.17/?
HSL Mathematical Software Library<https://www.hsl.rl.ac.uk/download/coinhsl-archive-linux-x86_64/2014.01.17/>
Currently only free licences are available on line. Further information on commercial licencing is available via our licencing page. To request a commercial licence please contact us by email: ***@***.***
www.hsl.rl.ac.uk

________________________________
De : Mahsa Parsapour ***@***.***>
Envoyé : lundi 21 février 2022 10:02
À : pyomeca/bioptim ***@***.***>
Cc : Eve Charbonneau ***@***.***>; Comment ***@***.***>
Objet : Re: [pyomeca/bioptim] Installation of HSL solvers (Issue #443)


The issue I have is the library’s name is “libcoinhsl.sa”. I put in the directory as you mentioned. The name is the library does not match.

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpyomeca%2Fbioptim%2Fissues%2F443%23issuecomment-1046968567&data=04%7C01%7Ceve.charbonneau.1%40umontreal.ca%7Ca5ac9a10ec4847b5be8408d9f54b2333%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637810525326181902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=du9hkjvva9wLvrCnPzdk0Ljn8LPD1HHLEdarPWW5%2F9A%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMERHFIXMBZA776WZF3UK33U4JHXFANCNFSM5OML22EA&data=04%7C01%7Ceve.charbonneau.1%40umontreal.ca%7Ca5ac9a10ec4847b5be8408d9f54b2333%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637810525326181902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QMBNec%2BD0zYV85FgUyOOBXmohN35F6OwX%2BcWdAVWT1w%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ceve.charbonneau.1%40umontreal.ca%7Ca5ac9a10ec4847b5be8408d9f54b2333%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637810525326181902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AzFKfOuDYtoXLJCPjPsNJcxBOgB4oRpaKHJxCFhnynU%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ceve.charbonneau.1%40umontreal.ca%7Ca5ac9a10ec4847b5be8408d9f54b2333%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637810525326338120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zjl6oiNvpfZk5cbG%2BjF5susQQWLxIRkQcJSxSLFv6TU%3D&reserved=0>.
