### ISSUE TITLE
Continuity constraints are not well displayed in direct collocation

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#447]
The solver indicates it converged, but the plot looks like it didn't succeed to satisfy the continuity constraints.
![image](https://user-images.githubusercontent.com/40755537/155184101-0796355f-562b-4a95-8751-3a9b71351738.png)
The live plot may not have been designed for DC.

**Comment by pariterre** [comment]
@Ipuch Could you provide a minimal example to work from
