### ISSUE TITLE
Animate tracked markers automatically in sol.animate

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#455]
Hi,

It would be nice to automatically provide tracked markers to the `sol.animate` when using TRACK_MARKERS. 

What do you think?

I'm just concerned about how to manage interpolation.

@aceglia

**Comment by pariterre** [comment]
This is a duplicate of #340

**Comment by Ipuch** [comment]
https://github.com/pyomeca/bioptim/blob/ab0bb6966732b4450989b338e38ffa0dff238c3a/bioptim/optimization/solution.py#L938-L948

We should add this line in the loop if there is a target with track_marker function:
```python all_bioviz[-1].load_experimental_markers(markers) # expr markers array(3, nmarkers, frames) ```
