### ISSUE TITLE
Expected target shape

### ISSUE THREAD

**Issue by thasaarah** [pyomeca/bioptim#471]
The marker tracking objective function (ObjectiveFcn.Mayer.TRACK_MARKERS) expects the target's shape to be (3,1), corresponding to the position of a single marker in three dimensions. The objective function also accepts a target with an additional component representing the frames, making the target's shape (n_dimensions, n_markers, n_frames). 

When the target is defined as the markers for a given event, its shape is (n_dimensions, n_markers), which isn't compatible with the expected input.

To fix this issue, [:, :, np.newaxis] was added to each target to modify the target's shape to (n_dimensions, n_markers, 1).

**Comment by EveCharbie** [comment]
Fixed :)
