### ISSUE TITLE
[Release 2.2.2] sol.graphs crashes if mayer term in objective

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#478]
Error obtained with either sol.graphs or solve(show_online=True):

line 682, in update_data
    if self.plot_func[key][i].parameters["penalty"].transition:
KeyError: 'penalty'

**Comment by EveCharbie** [comment]
@Julo0 will look at this issue.
@fbailly do you remember the case causing this error? Because example_multiphase has a Mayer term and both sol.graphs and show_online_optim work fine.

**Comment by EveCharbie** [comment]
Got the same error with this objective:
objective_functions.add(ObjectiveFcn.Lagrange.MINIMIZE_STATE, key='q', node=Node.ALL_SHOOTING, index=elbow_dofs, target=np.zeros(len(elbow_dofs)), weight=10000, phase=0)
Code available here: https://github.com/EveCharbie/VisionOCP/blob/main/TechOpt831.py

@lsechoir would you have have time to look into it ?
