### ISSUE TITLE
Dangerous commits

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#493]
@aceglia, @pariterre 

This seems highly dangerous! Why would you only set an option if it was not already there and ignore the set otherwise? Also, what if this new key does not exist in Ipopt, we offer no waranty here... If you need this for some sort of hacking behind the bioptim wall, please be very specific in the title of the function (set_option_unsafe or something like that)

https://github.com/pyomeca/bioptim/blob/a739cf7d2afd2530ce15e6aad49c9a1907a423cc/bioptim/interfaces/solver_options.py#L369-L370

This seems highly dangerous! Why would you only set an option if it was not already there and ignore the set otherwise? Also, what if this new key does not exist in Ipopt, we offer no waranty here... If you need this for some sort of hacking behind the bioptim wall, please be very specific in the title of the function (set_option_unsafe or something like that)

https://github.com/pyomeca/bioptim/blob/a739cf7d2afd2530ce15e6aad49c9a1907a423cc/bioptim/interfaces/solver_options.py#L462-L466

I disagree with this. I understand why you made that, but what if someone change the order in the future. All the setter bellow can be called individually. There is no reason to force the user to know what order we decided (emphasised by the fact that there is no documentation on the method, which is normal because of the the fact it is an overloaded method if I recall well). Moreover, changing the signature of an overloaded method is bad practise (I did not open your PR in an editor, but this is probably overlighted saying exactly this). Please remove

https://github.com/pyomeca/bioptim/blob/a739cf7d2afd2530ce15e6aad49c9a1907a423cc/bioptim/interfaces/solver_options.py#L569-L571

Please change this in the base class too

https://github.com/pyomeca/bioptim/blob/a739cf7d2afd2530ce15e6aad49c9a1907a423cc/bioptim/interfaces/solver_options.py#L598-L603

**Comment by aceglia** [comment]
@Ipuch You can close this one :)
