### ISSUE TITLE
Load and save is no more retro-compatible

### ISSUE THREAD

**Issue by rapidnico** [pyomeca/bioptim#533]
When saving a file on the dcd73128d40f9db7e1c0f208ba707a49e4b767ec commit, it is not possible to open it after the c140068ed0ab5869ea380c2ab16b8df85619e19e commit. The error is "ValueError: 'user' is not a valid ConstraintType" . Thus i wasn't able to reopen previously saved files.

**Comment by Ipuch** [comment]
I think we should store a .bo file for each release of bioptim in the test folder to test if we are still able to reload it.
@pariterre.

**Comment by Ipuch** [comment]
addressed in # #538 #535

**Comment by pariterre** [comment]
bioptim is NOT retrocompatible. Therefore it is expected that commits are incompatible
