### ISSUE TITLE
bioptim.ConstraintFcn.CONTACT_FORCE doesn't exist?

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#537]
Hello!

I am looking through the ConstraintFcn options and in your README.md I saw there's CONTACT_FORCE, but apparently it doesn't exist anymore when I import bioptim and run the dir() command:

```Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bioptim
>>> dir(bioptim.ConstraintFcn)
['CONTINUITY', 'CUSTOM', 'NON_SLIPPING', 'PROPORTIONAL_CONTROL', 'PROPORTIONAL_STATE', 'SUPERIMPOSE_MARKERS', 'TIME_CONSTRAINT', 'TORQUE_MAX_FROM_Q_AND_QDOT', 'TRACK_ANGULAR_MOMENTUM', 'TRACK_COM_POSITION', 'TRACK_COM_VELOCITY', 'TRACK_CONTACT_FORCES', 'TRACK_CONTROL', 'TRACK_LINEAR_MOMENTUM', 'TRACK_MARKERS', 'TRACK_MARKERS_VELOCITY', 'TRACK_MARKER_WITH_SEGMENT_AXIS', 'TRACK_QDDOT', 'TRACK_SEGMENT_WITH_CUSTOM_RT', 'TRACK_STATE', '__class__', '__doc__', '__members__', '__module__']
```

Could you kindly verify whether CONTACT_FORCE is renamed to something else, or if it's obsolete? Thank you!

Best,
Jan

**Comment by Ipuch** [comment]
Hello !
Thanks you for trying bioptim :+1: 

I got a look at it. Indeed, it looks to me that this constraint is obsolete. Get a look at the getting started example: `example_inequality_constraint.py`.

Contact are handled directly by a key word in the dynamics that states `with_contact=True` .

Let me know if you have more issue with this.

Regards,

Pierre

**Comment by jcllau** [comment]
Hi Pierre,

Thanks for confirming that! I have another question related to constraints. What's the difference between 'ALL' and 'ALL_SHOOTING', and what is 'DEFAULT'? 

I see those options when doing the dir() command, but don't see a description for them in the README.md:

```>>> import bioptim
>>> dir(bioptim.Node)
['ALL', 'ALL_SHOOTING', 'DEFAULT', 'END', 'INTERMEDIATES', 'MID', 'PENULTIMATE', 'START', 'TRANSITION', '__class__', '__doc__', '__members__', '__module__']
```

Best,
Jan

**Comment by Ipuch** [comment]
node = ALL_SHOOTING refers to all the node except the last one .
node = ALL refers to all the node including the last one.

It comes from the fact that when you specify the number of shooting node ns, we actually get ns + 1 values because we integrate from the ns node once, giving an extra arrival node for the last shooting node ns.

**Comment by jcllau** [comment]
Got it. I may (or may not) have more questions coming up regarding bioptim in the next little while. Thanks for the speedy responses!
