### ISSUE TITLE
Contacts 

### ISSUE THREAD

**Issue by MennatallahRihan** [pyomeca/bioptim#540]
Hello,
Regarding the contact points defined in the bioMod file, if I am not mistaken, it seems they are always active in the problem. How would one implement contact constraints that turn on or off based on the phase in the problem? 
I have been using TRACK_CONTACT_FORCE in the constraints hoping that is responsible for turning it on or off but it doesn't seem to be working.

Thanks!

**Comment by Ipuch** [comment]
Hello,

Thank you for trying bioptim ! :)

Good question, then you have to provide one .biomod file per phase. you can gather them into a tuple.
Have a look at the class OptimalControlProgram : 

https://github.com/pyomeca/bioptim/blob/dc16e58efa8dde0679ee73a2694cd2c1301e4082/bioptim/optimization/optimal_control_program.py#L143

Also you can have a look at the example of the bioptim paper, the examples are provided in another repo:

https://github.com/s2mLab/BioptimPaperExamples/blob/ef9607065f788324fa0b9132aeab93e2dc993ab0/gait/main.py#L19-L24

Let me know if is solved the problem.

Regards,

Pierre

**Comment by MennatallahRihan** [comment]
Hello,

Thank you for clearing that up, then I believe simply doing multiple biomod files will clear up my problem. I'll look into the examples.

Thanks again!
Menna

**Comment by Ipuch** [comment]
Perfect !
