### ISSUE TITLE
Is it possible to specify directions when constraining marker with SUPERIMPOSE_MARKERS?

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#549]
Hello!

Is there a way to specify the directions when constraining the position of a marker with bioptim.ConstraintFcn.SUPERIMPOSE_MARKERS? For instance, I would like to fix 3 directions for the first marker, 2 directions for the second marker, and 1 direction for the third, so that I can avoid redundant constraints. If this cannot be done, does each constraint.add(...) with SUPERIMPOSE_MARKERS constrain three directions of the specified marker location?

**Comment by Ipuch** [comment]
Hi jcllau,

You can use the keyword `index=[0,1,2]`, `index=[0,1]` and `index=[0]`. for the first, second and third constraints. It respectively refer to axis xyz, xy and x

**Comment by jcllau** [comment]
Awesome. Thank you!
