### ISSUE TITLE
ocp_graph time max_bound doesn't seem to reflect max_bound stated in the code

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#550]
Hello!

I was running the optimal_time_ocp/multiphase_time_constraint.py example with the ocp_graph enabled.

In the code, 
```
time_min = [1, 3, 0.1]
time_max = [2, 4, 0.8]
```
Although these values are reflected under the "Constraints" block of the ocp_graph pdf, I notice that the "Time" block shows the max_bound to be equal the min_bound.

![image](https://user-images.githubusercontent.com/89914331/194401191-4b28b433-7f76-4729-a982-3f1be3d815a7.png)

I'm not sure if this is simply a display error. Nonetheless, I would like to bring it to your attention :)

Best,
Jan

**Comment by Ipuch** [comment]
Hi,

thanks for reporting! 

It certainly is a display error.

pdf graphs are not well-maintained, so don't trust them 100%.

Regards,

Pierre

**Comment by EveCharbie** [comment]
@rapidnico will look at this issue

**Comment by mickaelbegon** [comment]
@rapidnico 
https://github.com/pyomeca/bioptim/blob/5027e98629690ba3de93de9355a843f2b1f2219e/bioptim/gui/graph.py#L253

**Comment by Ipuch** [comment]
issue solved !
