### ISSUE TITLE
How to change ocp plot names?

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#554]
Hello!

I was told the way to change the legend on biorbd is 
```
plt.legend(["upperArm_R","upperArm_L","LowerArm_R","LowerArm_L"],loc="best")
```

I would like to change the legend on my ocp plots on bioptim. However, I can't find any related info on the documentation, looked into the classes and parameters, and even tried ways to change the legend on bioptim based on the biorbd version, but nothing works and also I don't seem to find anything (or am I looking at the wrong spots?). Is there an equivalent approach on bioptim? :)

Best,
Jan

**Comment by Ipuch** [comment]
Hello,


Indeed it is not possible to directly change the default plots of the bioptim.

But you can create your own custom plots with this type of commands:

```python
ocp.add_plot(
            "name of the window", lambda t, x, u, p: your_custom_function(t,x,u,p,nlp), phase=i, legend=["title11", "title12", "title21", "title22"]
        )
```

with this you'll be able to choose the title of each subplot with the legend argument, have look to the getting started example custom_plotting.py 

Regards,
Pierre

**Comment by Ipuch** [comment]
Hi @jcllau,

Did it answer your question? Am I able to close the issue?

**Comment by jcllau** [comment]
Hi @Ipuch ,

Sorry for the very delayed response! Thanks for the command. So far it's working for me, though I wonder if it's also possible to show the bounds on the custom plots as well? I looked into the custom_plotting.py for an example and even penalty_option.py for add_plot options, but can't find anything.

Best,
Jan

**Comment by jcllau** [comment]
Woops. Sent that question too soon. I figured it out by looking at gui/plot.py by setting bounds=x_bounds[0][0:nDof] inside the add_plot function :)

**Comment by Ipuch** [comment]
Great, Enjoy Bioptim !
