### ISSUE TITLE
sol.animate() is getting (really) slow after a few loops

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#557]
Is that behavior noticed on other setups than mine ?
Is that a bioviz issue, or related to bioptim only ?

**Comment by fbailly** [comment]
For instance, juste play the pendulum example, wait and see !

**Comment by Julo0** [comment]
Two of us have the same problem

**Comment by pariterre** [comment]
Never noticed that! That's definitely bioviz side

**Comment by Ipuch** [comment]
Moved to bioviz https://github.com/pyomeca/bioviz/issues/87

**Comment by pariterre** [comment]
Found the bug, it was the arrow of gravity that was repeatedly added :)
