### ISSUE TITLE
Plot target according index

### ISSUE THREAD

**Issue by AntoineLeroy** [pyomeca/bioptim#575]
When you put a target and an index in the objective function, the plot of the target is on the first graph even if it is related to an other graph.
Example : I put a target for the q of the second dof and the program plot the target on the q graph of the first dof.

**Comment by Ipuch** [comment]
Start here to debug:

```python 3 

all_pn.ocp.add_plot(
                self.target_plot_name,
                plot_function,
                color="tab:red",
                plot_type=plot_type,
                phase=all_pn.nlp.phase_idx,
                axes_idx=Mapping(self.rows),
                node_idx=self.node_idx,
            )```
