### ISSUE TITLE
mapping documentation

### ISSUE THREAD

**Issue by lsechoir** [pyomeca/bioptim#580]
Docstring of mapping class says that if a negative value is given, value should be 0. When running the example, returns 
array([[ 0.1],
       [ 0.2],
       [ 0.2],
       [-0.4],
       [ 0.6],
       [ 0.2]])

    Mapping of index set to a different index set

    Example of use:
        - to_map = Mapping([0, 1, 1, 3, -1, 1], [3])
        - obj = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
        - mapped_obj = to_map.map(obj)
    Expected result:
        - mapped_obj == np.array([0.1, 0.2, 0.2, -0.4, 0, 0.1])

    Attributes
    ----------
    map_idx: list[int]
        The actual index list that links to the other set, an negative value links to a numerical 0
    oppose: list[int]
        Index to multiply by -1

@pariterre what is the good one (documentation, code), so i can open a PR

**Comment by EveCharbie** [comment]
Code is good numerical zero would be used if there was a None in the Mapping.

**Comment by pariterre** [comment]
Done
