### ISSUE TITLE
graphs merge when done in a loop 

### ISSUE THREAD

**Issue by lsechoir** [pyomeca/bioptim#596]
several optimization are done in a loop, if the optimal solution is found then the graphs are saved. It looks like the graphs are merging together after a few iterations. 
![CONSTRAINTS](https://user-images.githubusercontent.com/118196452/212768520-ea5338ea-5b0a-4450-9ce5-cbbe5eda6047.png)
![OBJECTIVES](https://user-images.githubusercontent.com/118196452/212768521-eb87a7d5-97e1-4ae6-91c6-3fd7a1ac6b19.png)
![qddot_states](https://user-images.githubusercontent.com/118196452/212768522-c495c958-fd51-4648-9920-e6822c7348a6.png)
![qdot_states](https://user-images.githubusercontent.com/118196452/212768523-7d7b46ff-ab39-4bc7-97d4-e0fc9d11b549.png)
![q_states](https://user-images.githubusercontent.com/118196452/212768524-7a4fdcf2-b1c7-4395-990a-212997f23bcb.png)

**Comment by Ipuch** [comment]
Please clarify, with a minimal example (e.g. pendulum). So that we can reproduce the bug.

**Comment by Ipuch** [comment]
This is the expected behavior. If you want to fix this. you would need to add, a new features it would look like something like this:
```python3 
sol.graphs(superimpose_with_previous=False) 
```

**Comment by Ipuch** [comment]
@lsechoir is it still true or has it been fixed ?

**Comment by lsechoir** [comment]
@Ipuch  It has not been fixed

**Comment by EveCharbie** [comment]
Does not seem to be a problem anymore. I tried it on the multi-start example.
