### ISSUE TITLE
AttributeError: 'MuscleGeometry' object has no attribute 'musclesPointsInGlobal'

### ISSUE THREAD

**Issue by tiagocoelhoma** [pyomeca/bioptim#603]
Hi everyone!

I am facing some troubles while simulating some examples in this new v3.0.0 (which was working previously).
For instance, while simulating the "static_arm_with_fatigue.py", I get the following error:

_> ------------------------------
> Traceback (most recent call last):
>   File "C:\Users\tiago\develop\bioptim\bioptim\examples\fatigue\static_arm_with_fatigue.py", line 213, in <module>
>     main()
>   File "C:\Users\tiago\develop\bioptim\bioptim\examples\fatigue\static_arm_with_fatigue.py", line 209, in main
>     sol.animate(show_meshes=True)
>   File "C:\Users\tiago\develop\bioptim\bioptim\optimization\solution.py", line 1375, in animate
>     all_bioviz.append(bioviz.Viz(biorbd_model.path, **kwargs))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\tiago\miniconda3\envs\bioptim\Lib\site-packages\bioviz\__init__.py", line 233, in __init__
>     tp = np.zeros((3, len(musc.position().musclesPointsInGlobal()), 1))
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'MuscleGeometry' object has no attribute 'musclesPointsInGlobal'_

If you run this example, you should problably get the same error.

**Comment by Ipuch** [comment]
Hi Tiago,

Thanks again for trying bioptim.

The problem comes from the version of bioviz. Your biorbd, bioptim, seems up to date. But our bioviz package isn't, we'll need to release a new version otherwise you can use the source code.

We'll let you know asap.

Thanks for reporting.

**Comment by Ipuch** [comment]
We updated the package https://github.com/pyomeca/bioviz/releases/tag/Release_2.3.0
Normally, it will be updated on conda-forge in the following hours.
Let me know if it works for you
