### ISSUE TITLE
Negative cost function value on a squared term

### ISSUE THREAD

**Issue by jcllau** [pyomeca/bioptim#606]
Hi! My OCP code has three types of objective terms (which are each split into 2, hence a total of 6 entries). MINIMIZE_CONTROL and minimize_torque are squared because I enabled quadratic=True. However, I noticed that the first MINIMIZE_CONTROL line in PHASE 1 has a negative value, which puzzled me because this term is squared.

I would like to know what the non-bracketed and bracketed values mean and reflect. Thank you :)

```
---- COST FUNCTION VALUES ----
PHASE 0
MINIMIZE_CONTROL:  1144.47 (weighted 2430.4164886932294)
MINIMIZE_CONTROL:  269.69 (weighted 235.72926110327882)
minimize_torque:  2503.39 (weighted 4341.460288689988)
minimize_torque:  63.36 (weighted 8.310218601801353)
minimize_mechanical_work:  835.14 (weighted 11.620355156177517)
minimize_mechanical_work:  714.15 (weighted 29.81047553809367)

PHASE 1
MINIMIZE_CONTROL: -419.76 (weighted 5329.359502085707)
MINIMIZE_CONTROL:  1.99 (weighted 351.94016862854016)
minimize_torque:  2044.34 (weighted 7238.34810835377)
minimize_torque:  214.35 (weighted 36.985728232356955)
minimize_mechanical_work:  1876.67 (weighted 85.85266282644997)
minimize_mechanical_work:  764.19 (weighted 104.87824662935074)

Sum cost functions: 20204.711504538747
------------------------------
```

**Comment by pariterre** [comment]
Dear @jcllau 
The version of bioptim you seem to run is a bit old. The number before the `()` is the unweighted and unsquared value. The actual cost is the `weighted` cost which is in `()`. We indeed found it was confusing and changed that later.
