### ISSUE TITLE
phase mapping with a custom model with no q

### ISSUE THREAD

**Issue by Kev1CO** [pyomeca/bioptim#609]
We try to implement Ding Model but we are blocked by phase mapping that requires nb_q dans dof_names, which makes no sense for us.

https://github.com/pyomeca/bioptim/blob/1d2a2f038a2a8fcc0afd0851b5f388000142803d/bioptim/optimization/optimal_control_program.py#L457-L459

How could we modify the code to make custom models works ?
@ipuch @EveCharbie  @pariterre

**Comment by pariterre** [comment]
Dear @Kev1CO 
Now that BioModel is the Protocol, we are free to modify the core of bioptim without breaking things too much. @Ipuch maybe we could remove `nb_q`, `nb_qdot`, ..., from `bioptim`. Then we could find a way to return the state/control names and get the `nb` of them (without a priori knowledge of what is a state). This would be a large refactor, but would prevent this kind of problem.

That said, @Kev1CO, for your problem, you simply have to return nb_q = 0

**Comment by pariterre** [comment]
This is now fixed in #612
