### ISSUE TITLE
model with no control

### ISSUE THREAD

**Issue by Kev1CO** [pyomeca/bioptim#610]
Our Model is only controlled by time, so our controls are empty.
Bioptim crashed, here:
https://github.com/pyomeca/bioptim/blob/1d2a2f038a2a8fcc0afd0851b5f388000142803d/bioptim/optimization/optimization_variable.py#L195-L217

Would it be possible to run a model without controls.

@pariterre  @EveCharbie  @Ipuch

**Comment by pariterre** [comment]
Dear @Kev1CO 
Optimal control implies a control. If you don't have controls, there is no point using an Optimal control schema. I am not sure how bioptim is relevent in your case

**Comment by Ipuch** [comment]
In the model we use, time "controls" the system dynamics. that's why there are no controls.

**Comment by pariterre** [comment]
I understand, but this is still not an optimal control program, it is `calculus of variation` program which bioptim is not designed to solve...

**Comment by Ipuch** [comment]
We succeeded
