### ISSUE TITLE
Scaling shape with derivative=True

### ISSUE THREAD

**Issue by AnaisFarr** [pyomeca/bioptim#620]
objective_functions.add(ObjectiveFcn.Mayer.MINIMIZE_MARKERS, node=Node.ALL, weight=0.01, phase=2, reference_jcs=0, derivative=True)

The problem is at line 261 of interface_utils in the         if _penalty.derivative or _penalty.explicit_derivative:

@EveCharbie will take care of this

**Comment by Ipuch** [comment]
Is it still true?

**Comment by EveCharbie** [comment]
Yes, I hope to have time to fix this soon
