### ISSUE TITLE
nlp.x_scaling["all"] not taking muscles into account

### ISSUE THREAD

**Issue by fbailly** [pyomeca/bioptim#622]
Hey,

I have an example running with muscle activations as states.

The instantiation of the OCP class crashes because of a dimension mismatch in bioptim/optimization/optimization_vector.py, line 370.

This comes from the fact that my state vector is not of the same size as the scaling vector. The later lacks as many components as the size of the muscle vector. 

@EveCharbie, I think your the best person to fix that ;)

Thanks !

**Comment by EveCharbie** [comment]
True that, my lack of interest for muscles has spoken oupsi!
It is weird it is not tested though :/ Could you provide a piece of code to speed up my process of writing a new test for that?
When do you need this to be fixed? I might have time end of next week.

**Comment by fbailly** [comment]
@EveCharbie it is not urgent as I found a workaround.
The problem occurs when muscles are declared as states and that an InitialGuess is provided by default, e.g.: x_init=IntialGuess().
When the initial guess is built with the proper dimensions (nbq+nbqdot+nbmuscles), the scaling works.
Reach out when you will tackle this issue, I can provide an error throwing example :)

**Comment by Ipuch** [comment]
Indeed, it should be fixed today with #617

**Comment by Ipuch** [comment]
@EveCharbie can we close this ?

**Comment by pariterre** [comment]
This should now be solved #684
