### ISSUE TITLE
Installation Issues (OS Windows 11 & Ubuntu 22.04 on WSL)

### ISSUE THREAD

**Issue by NicolasGrandin** [pyomeca/bioptim#638]
Hi everyone,

I'm new to Bioptim, and I'm trying to use it on my computer (OS: Windows 11 & Ubuntu 22.04 on WSL). 
As suggested, I used Ubuntu with WSL to download miniconda and then Bioptim using.
However, I couldn't finish the installation since I couldn't find where the setup.py file is.
Indeed, it is mentionned in the installation section "the root folder", so I took a look in the linux "root" folder as in the miniconda folder butI didn't find it...

As a consequence, when I try to run the first practical example, the system raises an error "ImportError : cannot import name 'BiorbdModel' from 'bioptim'":

import biorbd_casadi as biorbd
from bioptim import (
    BiorbdModel,
    OptimalControlProgram,
    DynamicsFcn,
    Dynamics,
    Bounds,
    
    InitialGuess,
    ObjectiveFcn,
    Objective,
)

Thank you in advance !

**Comment by pariterre** [comment]
> However, I couldn't finish the installation since I couldn't find where the setup.py file is.

Hi @NicolasGrandin !
If you install bioptim from conda, you do not need to perform any `python setup.py install`, as it is already installed from conda. You just have to run the command: `conda install bioptim -cconda-forge`. If you want to install bioptim from the source, then you indeed have to do `python setup.py install`. Unless you want to modify the core of bioptim, there is not really any reason to go that way though

> Indeed, it is mentionned in the installation section "the root folder", so I took a look in the linux "root" folder as in the miniconda folder butI didn't find it...

In the case you are installing bioptim from conda, you do not need to navigate to the bioptim root folder either.

In brief, after you have installed anaconda (or miniconda), you simply:
1. Restart your terminal, then you should see that your prompt start with: `(base)`.
2. (optional) You can create an environment dedicated to bioptim or install in base (if you want to create an environment, you run the commands: `conda create -n ENVIRONMENT_NAME`, then `conda activate ENVIRONMENT_NAME`. 
3. Once you have loaded the environment, you run: `conda install bioptim -cconda-forge`
4. You should be good to go

**Comment by pariterre** [comment]
Hi again!

`pendulum.bioMod` is an example file of biorbd. As it says, it is basically a pendulum. It is therefore not a part of bioptim per se, but should be distrubuted anyway with the examples. If you navigate in `bioptim/examples/getting_started/models/`, you should find it. Alternatively, you will find it in the github repo. Don't forget to download the stl files as well :)

**Comment by NicolasGrandin** [comment]
Hi !
Ok thank you for your help and information I'll do that !
