### ISSUE TITLE
Commit addressing node specific dynamics breaks multi-threading

### ISSUE THREAD

**Issue by tiagocoelhoma** [pyomeca/bioptim#642]
Hello!

We have found out that commit "[addressing node specific dynamics](https://github.com/pyomeca/bioptim/commit/3e33bd5c14622ce39f99a3845549a5464d01ee08#diff-4d417304f8eca5ffc2d7ee72a6b32b555e2390e628df95cf5c964e612de48a2b)" limits the number of threads used to 1 while solving, even though the parameter n_threads is specified correctly (i.e. n_threads > 1).

If possible, could you please take a look?

Thank you very much.

**Comment by Ipuch** [comment]
Can you provide a minimum example that reproduce the bug ?

**Comment by tiagocoelhoma** [comment]
Hi @Ipuch 
we have observed that, after the commit mentioned above, there was a limitation on the number of threads (any code where the parameter n_threads>1). @fbailly observed that it was not happening before this commit.

**Comment by pariterre** [comment]
Hi @tiagocoelhoma !
This is indeed the expected results of these modification. We however forgot it would have these adverse effects.

Currently, we are rewriting the core of the states and controls (#630). I will make sure to reintroduce the multithreading when this PR is accepted. Expect few weeks of development though...

Sorry about that!

**Comment by Ipuch** [comment]
Hi @tiagocoelhoma,
We fixed the problem, if you want to restore multithreaded function. You have to declare
```python3
OptimalControlProgram(...
assume_phase_dynamics=True,)
```
