### ISSUE TITLE
Parameter implementation should be uniformed with the other variables 

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#686]
The bound, init and scaling are implemented differently (which, I think, only comes from the fact that they were not implemented at the same time)
self.parameters_in_list is a weird object, it should be closer to a OptimizationVariableList

**Comment by EveCharbie** [comment]
Also fix the targets scaling (send unscaled value)

**Comment by Ipuch** [comment]
Is it resolved in #684 ? @pariterre

**Comment by EveCharbie** [comment]
Should implement ParameterContainer(VariableContainer) and just overwrite the methods that do not apply or have to be changed.
For now only the version unscaled of the parameters exist (which means that the value in IPOPT is fine, but if we use the parameter in a penalty, the value is wrong!).
Thus, we should also check the code for every time we unscale the parameters and use parameter_unscaled instead (in the dynamics, in the bounds, init, ...).
