### ISSUE TITLE
Bioptim is slower than it used to be.

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#713]
I am quite sure now that the iterations are slower than before. I thought it was a problem with OCP1, but I have the same issue with OCP3 since I merged master. And we are definitely slower than the Matlab version. I don't know if it is our fault, the new casadi version, our MA57 version that is too old.... But I think we SHOULD investigate it.

**Comment by pariterre** [comment]
What do you call OCP1 and OCP3?

**Comment by EveCharbie** [comment]
Internal business: c'est le nom qu'on a donné aux calculateurs.

**Comment by pariterre** [comment]
Problem comes from an expand=False in `joints_acceleration_driven` in `configure_problem.py`. I suspect it was done because it may run out of memory. I suggest we accept `expand` as a parameter in dynamic list so it can be managed from the prepare_ocp

**Comment by pariterre** [comment]
After having a look, there is no easy way to change the current behavior of the function. It has to be on a "case-by-case basis", meaning it is possible to do so for the specific `joints_acceleration_driven`, but it won't transfer to the other cases (unless we implement this for all of them

**Comment by Ipuch** [comment]
Closed since this is a very specific case, partly addressed in #727 so that expand is always taken into account.
