### ISSUE TITLE
Can I add constraintList/objectiveList.add_or_replace_to_penalty_pool()?

### ISSUE THREAD

**Issue by EveCharbie** [pyomeca/bioptim#720]
@pariterre do you see any inconvenience if I add this method to copy what is done in MultinodePenalties?
It is just adding a method doing a for loop on penalties.
We can talk about it on PR review.

**Comment by Ipuch** [comment]
So we should remove .update_constraint method ?

**Comment by pariterre** [comment]
add_or_replace.. is meant to be used internally. update_constraint is the API for the user that should call add_or_replace properly, depending if the constraint is attached to an nlp or directly to ocp.
I think it should stay. The other alternative is that add_or_replace... name is replace to update_ocp (or something like so)
