### ISSUE TITLE
print_cost does not display the right value anymore in pendulum example

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#748]
56  4.1582594e+01 2.18e-13 8.82e-12  -7.0 2.99e-06    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 56

                                   (scaled)                 (unscaled)
Objective...............:   4.1582594261527476e+01    4.1582594261527476e+01
Dual infeasibility......:   8.8245666159473131e-12    8.8245666159473131e-12
Constraint violation....:   2.1760371282653068e-13    2.1760371282653068e-13
Variable bound violation:   8.4761051510895413e-09    8.4761051510895413e-09
Complementarity.........:   9.0917753405469641e-08    9.0917753405469641e-08
Overall NLP error.......:   9.0917753405469641e-08    9.0917753405469641e-08

Number of objective function evaluations             = 125
Number of objective gradient evaluations             = 57
Number of equality constraint evaluations            = 125
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 57
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 56
Total seconds in IPOPT                               = 0.506

EXIT: Optimal Solution Found.
      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
callback_fun  |   5.51ms ( 96.58us)   5.46ms ( 95.72us)        57
       nlp_f  | 451.00us (  3.61us) 449.59us (  3.60us)       125
       nlp_g  |  22.38ms (179.04us)  22.32ms (178.59us)       125
  nlp_grad_f  | 331.00us (  5.61us) 321.56us (  5.45us)        59
  nlp_hess_l  | 272.14ms (  4.86ms) 272.21ms (  4.86ms)        56
   nlp_jac_g  |  91.96ms (  1.59ms)  92.04ms (  1.59ms)        58
       total  | 506.18ms (506.18ms) 506.58ms (506.58ms)         1
Solver reported time: 0.506577932 sec
Real time: 0.5072171790016 sec

---- COST FUNCTION VALUES ----
PHASE 0
Lagrange.MINIMIZE_CONTROL: 1247.477827845824 (non weighted -0.17)

Sum cost functions: 1247.477827845824

**Comment by pariterre** [comment]
It seems that it is now fixed, closing!
