### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by pariterre** [pyomeca/bioptim#76]
Docstrings must deeply be reviewed

**Comment by mickaelbegon** [comment]
in dynamics.py change
Forward dynamics (q, qdot, qddot -> tau)
for 
Forward dynamics (q, qdot, tau-> qddot)

def forward_dynamics_muscle_excitations_driven
def forward_dynamics_muscle_excitations_and_torque_driven
def forward_dynamics_muscle_excitations_and_torque_driven_with_contact

**Comment by pariterre** [comment]
Done
