### ISSUE TITLE
Save and load extension possibility before deleting it

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#812]
Enhancement: Extend save Feature to Include Version and Commit Info in a Zipped File

We may not need to delete save and load in #804 

Description:

The goal of this enhancement is to modify the save method in Bioptim to provide more robust version tracking and compatibility checks for saved optimization solutions. The key features of this proposal include:

- [x] **Saving Bioptim Version and Git Commit Number**: When a user saves their work, the Bioptim version and the Git commit number at the time of saving should be recorded. This information is crucial for ensuring that the saved data is compatible with the version of Bioptim used for loading and further processing. Done in #806 

- [ ] **Zipping Saved Data with Version Info**: The saved data (including states, controls, parameters, etc.) and the version information (Bioptim version and commit number) will be saved in two separate files. These files will then be zipped together into a single archive. This helps to know info without having to import bioptim class.

- [ ] **Enhanced Data Portability and Version Compatibility Checks**: By including version information with the saved data, We could check if it is compatible with the current version commit.

This enhancement makes it easier to track and resolve any version-related issues that might arise during the loading and processing of saved data.

**Comment by EveCharbie** [comment]
Finally, I understood that @pariterre did not want to go in this direction as he removed what I previously did with git version.
Instead, I added an example on how we recommend to save the outputs in pendulum.

**Comment by EveCharbie** [comment]
It would be better to make a separate example with different ways to get the current version depending on the way bioptim was installed (conda-forge or local github available)
