### ISSUE TITLE
Testing solution outputs to manually display graphs of pendulum

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#813]
@Alpha2Shahiri we would like you to try the new interface in order to display the results in a Matplotlib graphs without using sol.graphs. It would largely help us to see if we did our job correctly.

You can do a PR on the pendulum.py to properly do it.

Wait for the next merge to start.

**Comment by Alpha2Shahiri** [comment]
Done. Thanks
"https://github.com/pyomeca/bioptim/pull/820"

**Comment by mickaelbegon** [comment]
@Alpha2Shahiri 
Why the PR has been closed?
