### ISSUE TITLE
Problem while plotting with multiphase and one node per phase

### ISSUE THREAD

**Issue by tiagocoelhoma** [pyomeca/bioptim#838]
Hello!!

I was wondering if you could help me with plot issues. 
I've been facing some plot issues when my problem is multiphased with one node per phase

I built a MWE to show the error.
[sandbox/models/static_arm_multiphase.py](https://github.com/tiagocoelhoma/bioptim/blob/8468455e4ac2872be0162a22954f057fdc897037/sandbox/models/static_arm_multiphase.py)

I added a error message indicating the problematic line and its related configuration (116)

Thank you very much for your time!

Best regards.
Tiago.

**Comment by fbailly** [comment]
probably related to  #781

**Comment by tiagocoelhoma** [comment]
Hello once again,

just to be more specific on this error. I think the previous message on this issue does not point to the version of the code with the file containing the message error. I indicate once again here (the codes are the same, just the error message was added):

https://github.com/tiagocoelhoma/bioptim/blob/ee8a50aa44116accc937186230dde80fde084c13/sandbox/static_arm_multiphase.py

Being more specific to this problem, I create a MWE with multi-phase with the objective to track a specific position and, when I ask for plotting the results, i get this error:

```
  File "/home/.../bioptim/bioptim/optimization/solution/solution.py", line 883, in graphs
    plot_ocp.update_data(self.vector)
  File "/home/.../bioptim/bioptim/gui/plot.py", line 696, in update_data
    y_data = self._compute_y_from_plot_func(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../bioptim/bioptim/gui/plot.py", line 790, in _compute_y_from_plot_func
    y_tp[axe_index, :] = tp[ctr, :]
                         ~~^^^^^^^^
IndexError: index 1 is out of bounds for axis 0 with size 1
```

The problem is intended to have one node per phase with a tracking objective (which is similar to what we are working one here, in another context).

If you define  `n_shooting=2` (or higher) it would be fine and the plots will come out. _But, letting it to  `n_shooting=1`, you will see the problem_. 

Also, it will plot OK if you comment the following:

```
        objective_functions.add(
            ObjectiveFcn.Mayer.TRACK_STATE,
            key="q",
            index=0,
            node=Node.END,
            target=1,
            weight=1e4,
            phase=n_phases-1,
        )
```

Unfortunately, this is not the our objective in this application. We need multi-phase with n_shooting=1 and the tracking state objective defined.

Hope it helps to understand it better.

**Comment by pariterre** [comment]
As far as I am concerned, n_shooting=1 will produce undefined behavior in general. I am actually surprise that you do not get error before that. I thought we were raising an error if n_shooting < 3. Why do you need multi-phase instead of a single phase?

**Comment by tiagocoelhoma** [comment]
Hello @pariterre 

I am working with a biomechanical example using Electrical Stimulation where the dynamics change at a given predefined interval which justifies the need for multi-phase. Within each phase, however, the dynamics should be called just once.

**Comment by pariterre** [comment]
I was asking because if the equations are the same, but should be only tweeked, you can use a single phase with PhaseDynamics.ONE_PER_NODE

**Comment by EveCharbie** [comment]
I think you would talk with @Kev1CO for the was to implement FES OCPs.
Can we close this issue?

**Comment by pariterre** [comment]
Fixed in an upcoming PR from @Kev1CO
