### ISSUE TITLE
ytick format on graphs

### ISSUE THREAD

**Issue by Ipuch** [pyomeca/bioptim#889]
Here is a suggestion instead of replacing tick values @pariterre 

# Define a formatter function
def format_func(value, tick_number):
    return f'{value:.2f}'

# Apply the formatter to the x and y axis
ax.xaxis.set_major_formatter(FuncFormatter(format_func))
ax.yaxis.set_major_formatter(FuncFormatter(format_func))

**Comment by pariterre** [comment]
Fixed in #890
